apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: spyrous/node_db_app:v24 #spyrous/node_db_app:v19
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 3000